In [1]:
import numpy as np
import pandas as pd
import json

In [279]:
csvdata = pd.read_csv('crimes-aggregated.csv')
df = pd.read_csv('csv.csv')
df.head()

   Unnamed: 0 Primary Type  Year  Arrest  Values
0           0        ARSON  2008   False    1170
1           1        ARSON  2008    True     118
2           2        ARSON  2009   False    1093
3           3        ARSON  2009    True     138
4           4        ARSON  2010   False     884

In [280]:
df = df.drop(['Unnamed: 0'], axis=1)
df.head()

  Primary Type  Year  Arrest  Values
0        ARSON  2008   False    1170
1        ARSON  2008    True     118
2        ARSON  2009   False    1093
3        ARSON  2009    True     138
4        ARSON  2010   False     884

In [281]:
df.columns = ['crime', 'year','arrest','values']
df.head()

   crime  year  arrest  values
0  ARSON  2008   False    1170
1  ARSON  2008    True     118
2  ARSON  2009   False    1093
3  ARSON  2009    True     138
4  ARSON  2010   False     884

In [282]:
df.loc[df.arrest != False, 'arrest'] = "arrest"
df.loc[df.arrest == False, 'arrest'] = "no_arrest"

In [289]:
df.head()

   crime  year     arrest  values
0  ARSON  2008  no_arrest    1170
1  ARSON  2008     arrest     118
2  ARSON  2009  no_arrest    1093
3  ARSON  2009     arrest     138
4  ARSON  2010  no_arrest     884

In [295]:
df["freq"] = "!" + df["arrest"].map(str) + ": " + df["values"].map(str) + "!"

In [296]:
df.head()

   crime  year     arrest  values               freq
0  ARSON  2008  no_arrest    1170  !no_arrest: 1170!
1  ARSON  2008     arrest     118      !arrest: 118!
2  ARSON  2009  no_arrest    1093  !no_arrest: 1093!
3  ARSON  2009     arrest     138      !arrest: 138!
4  ARSON  2010  no_arrest     884   !no_arrest: 884!

In [297]:
def get_nested_rec(key, grp):
    rec = {}
    rec['crime'] = key[0]
    rec['year'] = key[1]
    #rec['arrest'] = key[2]

    for field in ['arrest']:
        for field1 in ['freq']:
            rec[field1] = list(grp[field1].unique())
    return rec

In [258]:
def gnr(key,grp):
    rec = {}
    rec['arrest'] = key[0]
    
    for field in ['values']:
        rec[field] = list(grp[field].unique())
    return rec

def get_nested_rec(key, grp):
    rec = {}
    rec['crime'] = key[0]
    rec['year'] = key[1]
    
    #records = []
    for key, grp in df.groupby(['crime','year','arrest']):
        rec = gnr(key, grp)
        #records.append(rec)
    return rec

In [298]:
records = []
for key, grp in df.groupby(['crime','year']):
    rec = get_nested_rec(key, grp)
    records.append(rec)

records = dict(data = records)

In [299]:
def default(o):
    if isinstance(o, np.int64): return int(o)  
    raise TypeError

#json.dumps({'Values': np.int64(42)}, default=default)
print(json.dumps(records, indent=4,default=default))

{
    "data": [
        {
            "crime": "ARSON",
            "year": 2008,
            "freq": [
                "!no_arrest: 1170!",
                "!arrest: 118!"
            ]
        },
        {
            "crime": "ARSON",
            "year": 2009,
            "freq": [
                "!no_arrest: 1093!",
                "!arrest: 138!"
            ]
        },
        {
            "crime": "ARSON",
            "year": 2010,
            "freq": [
                "!no_arrest: 884!",
                "!arrest: 128!"
            ]
        },
        {
            "crime": "ARSON",
            "year": 2011,
            "freq": [
                "!no_arrest: 458!",
                "!arrest: 48!"
            ]
        },
        {
            "crime": "ASSAULT",
            "year": 2008,
            "freq": [
                "!no_arrest: 40230!",
                "!arrest: 10622!"
            ]
        },
        {
            "crime": "ASSAULT",
            "year": 2009,
            "freq": [
                "!no_arrest: 34304!",
                "!arrest: 11391!"
            ]
        },
        {
            "crime": "ASSAULT",
            "year": 2010,
            "freq": [
                "!no_arrest: 31537!",
                "!arrest: 9692!"
            ]
        },
        {
            "crime": "ASSAULT",
            "year": 2011,
            "freq": [
                "!no_arrest: 15260!",
                "!arrest: 5193!"
            ]
        },
        {
            "crime": "BATTERY",
            "year": 2008,
            "freq": [
                "!no_arrest: 120702!",
                "!arrest: 31009!"
            ]
        },
        {
            "crime": "BATTERY",
            "year": 2009,
            "freq": [
                "!no_arrest: 104198!",
                "!arrest: 32629!"
            ]
        },
        {
            "crime": "BATTERY",
            "year": 2010,
            "freq": [
                "!no_arrest: 97554!",
                "!arrest: 27286!"
            ]
        },
        {
            "crime": "BATTERY",
            "year": 2011,
            "freq": [
                "!no_arrest: 46385!",
                "!arrest: 14152!"
            ]
        },
        {
            "crime": "BURGLARY",
            "year": 2008,
            "freq": [
                "!no_arrest: 49300!",
                "!arrest: 3105!"
            ]
        },
        {
            "crime": "BURGLARY",
            "year": 2009,
            "freq": [
                "!no_arrest: 50665!",
                "!arrest: 2820!"
            ]
        },
        {
            "crime": "BURGLARY",
            "year": 2010,
            "freq": [
                "!no_arrest: 47012!",
                "!arrest: 2658!"
            ]
        },
        {
            "crime": "BURGLARY",
            "year": 2011,
            "freq": [
                "!no_arrest: 25358!",
                "!arrest: 1263!"
            ]
        },
        {
            "crime": "CRIM SEXUAL ASSAULT",
            "year": 2008,
            "freq": [
                "!no_arrest: 2481!",
                "!arrest: 535!"
            ]
        },
        {
            "crime": "CRIM SEXUAL ASSAULT",
            "year": 2009,
            "freq": [
                "!no_arrest: 2350!",
                "!arrest: 436!"
            ]
        },
        {
            "crime": "CRIM SEXUAL ASSAULT",
            "year": 2010,
            "freq": [
                "!no_arrest: 2028!",
                "!arrest: 411!"
            ]
        },
        {
            "crime": "CRIM SEXUAL ASSAULT",
            "year": 2011,
            "freq": [
                "!no_arrest: 1257!",
                "!arrest: 219!"
            ]
        },
        {
            "crime": "CRIMINAL DAMAGE",
            "year": 2008,
            "freq": [
                "!no_arrest: 98718!",
                "!arrest: 6801!"
            ]
        },
        {
            "crime": "CRIMINAL DAMAGE",
            "year": 2009,
            "freq": [
                "!no_arrest: 88851!",
                "!arrest: 6536!"
            ]
        },
        {
            "crime": "CRIMINAL DAMAGE",
            "year": 2010,
            "freq": [
                "!no_arrest: 72613!",
                "!arrest: 5088!"
            ]
        },
        {
            "crime": "CRIMINAL DAMAGE",
            "year": 2011,
            "freq": [
                "!no_arrest: 34749!",
                "!arrest: 2583!"
            ]
        },
        {
            "crime": "CRIMINAL TRESPASS",
            "year": 2008,
            "freq": [
                "!no_arrest: 11528!",
                "!arrest: 13077!"
            ]
        },
        {
            "crime": "CRIMINAL TRESPASS",
            "year": 2009,
            "freq": [
                "!no_arrest: 5832!",
                "!arrest: 15853!"
            ]
        },
        {
            "crime": "CRIMINAL TRESPASS",
            "year": 2010,
            "freq": [
                "!no_arrest: 5545!",
                "!arrest: 12404!"
            ]
        },
        {
            "crime": "CRIMINAL TRESPASS",
            "year": 2011,
            "freq": [
                "!no_arrest: 2242!",
                "!arrest: 6417!"
            ]
        },
        {
            "crime": "DECEPTIVE PRACTICE",
            "year": 2008,
            "freq": [
                "!no_arrest: 25242!",
                "!arrest: 4340!"
            ]
        },
        {
            "crime": "DECEPTIVE PRACTICE",
            "year": 2009,
            "freq": [
                "!no_arrest: 22489!",
                "!arrest: 4911!"
            ]
        },
        {
            "crime": "DECEPTIVE PRACTICE",
            "year": 2010,
            "freq": [
                "!no_arrest: 18826!",
                "!arrest: 3979!"
            ]
        },
        {
            "crime": "DECEPTIVE PRACTICE",
            "year": 2011,
            "freq": [
                "!no_arrest: 10227!",
                "!arrest: 2468!"
            ]
        },
        {
            "crime": "GAMBLING",
            "year": 2008,
            "freq": [
                "!no_arrest: 83!",
                "!arrest: 2313!"
            ]
        },
        {
            "crime": "GAMBLING",
            "year": 2009,
            "freq": [
                "!no_arrest: 10!",
                "!arrest: 1971!"
            ]
        },
        {
            "crime": "GAMBLING",
            "year": 2010,
            "freq": [
                "!arrest: 1834!"
            ]
        },
        {
            "crime": "GAMBLING",
            "year": 2011,
            "freq": [
                "!arrest: 736!"
            ]
        },
        {
            "crime": "HOMICIDE",
            "year": 2008,
            "freq": [
                "!no_arrest: 250!",
                "!arrest: 263!"
            ]
        },
        {
            "crime": "HOMICIDE",
            "year": 2009,
            "freq": [
                "!no_arrest: 242!",
                "!arrest: 218!"
            ]
        },
        {
            "crime": "HOMICIDE",
            "year": 2010,
            "freq": [
                "!no_arrest: 247!",
                "!arrest: 191!"
            ]
        },
        {
            "crime": "HOMICIDE",
            "year": 2011,
            "freq": [
                "!no_arrest: 259!",
                "!arrest: 178!"
            ]
        },
        {
            "crime": "INTERFERENCE WITH PUBLIC OFFICER",
            "year": 2008,
            "freq": [
                "!no_arrest: 239!",
                "!arrest: 920!"
            ]
        },
        {
            "crime": "INTERFERENCE WITH PUBLIC OFFICER",
            "year": 2009,
            "freq": [
                "!no_arrest: 89!",
                "!arrest: 1055!"
            ]
        },
        {
            "crime": "INTERFERENCE WITH PUBLIC OFFICER",
            "year": 2010,
            "freq": [
                "!no_arrest: 191!",
                "!arrest: 1336!"
            ]
        },
        {
            "crime": "INTERFERENCE WITH PUBLIC OFFICER",
            "year": 2011,
            "freq": [
                "!no_arrest: 66!",
                "!arrest: 982!"
            ]
        },
        {
            "crime": "INTIMIDATION",
            "year": 2008,
            "freq": [
                "!no_arrest: 410!",
                "!arrest: 112!"
            ]
        },
        {
            "crime": "INTIMIDATION",
            "year": 2009,
            "freq": [
                "!no_arrest: 384!",
                "!arrest: 78!"
            ]
        },
        {
            "crime": "INTIMIDATION",
            "year": 2010,
            "freq": [
                "!no_arrest: 338!",
                "!arrest: 44!"
            ]
        },
        {
            "crime": "INTIMIDATION",
            "year": 2011,
            "freq": [
                "!no_arrest: 129!",
                "!arrest: 42!"
            ]
        },
        {
            "crime": "KIDNAPPING",
            "year": 2008,
            "freq": [
                "!no_arrest: 641!",
                "!arrest: 76!"
            ]
        },
        {
            "crime": "KIDNAPPING",
            "year": 2009,
            "freq": [
                "!no_arrest: 528!",
                "!arrest: 58!"
            ]
        },
        {
            "crime": "KIDNAPPING",
            "year": 2010,
            "freq": [
                "!no_arrest: 553!",
                "!arrest: 51!"
            ]
        },
        {
            "crime": "KIDNAPPING",
            "year": 2011,
            "freq": [
                "!no_arrest: 235!",
                "!arrest: 31!"
            ]
        },
        {
            "crime": "LIQUOR LAW VIOLATION",
            "year": 2008,
            "freq": [
                "!no_arrest: 51!",
                "!arrest: 1772!"
            ]
        },
        {
            "crime": "LIQUOR LAW VIOLATION",
            "year": 2009,
            "freq": [
                "!no_arrest: 16!",
                "!arrest: 1475!"
            ]
        },
        {
            "crime": "LIQUOR LAW VIOLATION",
            "year": 2010,
            "freq": [
                "!no_arrest: 2!",
                "!arrest: 1424!"
            ]
        },
        {
            "crime": "LIQUOR LAW VIOLATION",
            "year": 2011,
            "freq": [
                "!no_arrest: 4!",
                "!arrest: 615!"
            ]
        },
        {
            "crime": "MOTOR VEHICLE THEFT",
            "year": 2008,
            "freq": [
                "!no_arrest: 34657!",
                "!arrest: 3050!"
            ]
        },
        {
            "crime": "MOTOR VEHICLE THEFT",
            "year": 2009,
            "freq": [
                "!no_arrest: 28345!",
                "!arrest: 2597!"
            ]
        },
        {
            "crime": "MOTOR VEHICLE THEFT",
            "year": 2010,
            "freq": [
                "!no_arrest: 33467!",
                "!arrest: 1967!"
            ]
        },
        {
            "crime": "MOTOR VEHICLE THEFT",
            "year": 2011,
            "freq": [
                "!no_arrest: 18443!",
                "!arrest: 946!"
            ]
        },
        {
            "crime": "NARCOTICS",
            "year": 2008,
            "freq": [
                "!no_arrest: 2009!",
                "!arrest: 90653!"
            ]
        },
        {
            "crime": "NARCOTICS",
            "year": 2009,
            "freq": [
                "!no_arrest: 700!",
                "!arrest: 86295!"
            ]
        },
        {
            "crime": "NARCOTICS",
            "year": 2010,
            "freq": [
                "!no_arrest: 174!",
                "!arrest: 82616!"
            ]
        },
        {
            "crime": "NARCOTICS",
            "year": 2011,
            "freq": [
                "!no_arrest: 70!",
                "!arrest: 38560!"
            ]
        },
        {
            "crime": "NON-CRIMINAL",
            "year": 2009,
            "freq": [
                "!no_arrest: 1!"
            ]
        },
        {
            "crime": "NON-CRIMINAL",
            "year": 2010,
            "freq": [
                "!no_arrest: 2!"
            ]
        },
        {
            "crime": "OBSCENITY",
            "year": 2008,
            "freq": [
                "!arrest: 26!"
            ]
        },
        {
            "crime": "OBSCENITY",
            "year": 2009,
            "freq": [
                "!no_arrest: 10!",
                "!arrest: 32!"
            ]
        },
        {
            "crime": "OBSCENITY",
            "year": 2010,
            "freq": [
                "!no_arrest: 12!",
                "!arrest: 49!"
            ]
        },
        {
            "crime": "OBSCENITY",
            "year": 2011,
            "freq": [
                "!no_arrest: 9!",
                "!arrest: 31!"
            ]
        },
        {
            "crime": "OFFENSE INVOLVING CHILDREN",
            "year": 2008,
            "freq": [
                "!no_arrest: 4101!",
                "!arrest: 1062!"
            ]
        },
        {
            "crime": "OFFENSE INVOLVING CHILDREN",
            "year": 2009,
            "freq": [
                "!no_arrest: 4065!",
                "!arrest: 1003!"
            ]
        },
        {
            "crime": "OFFENSE INVOLVING CHILDREN",
            "year": 2010,
            "freq": [
                "!no_arrest: 3656!",
                "!arrest: 931!"
            ]
        },
        {
            "crime": "OFFENSE INVOLVING CHILDREN",
            "year": 2011,
            "freq": [
                "!no_arrest: 1889!",
                "!arrest: 450!"
            ]
        },
        {
            "crime": "OTHER NARCOTIC VIOLATION",
            "year": 2008,
            "freq": [
                "!no_arrest: 2!",
                "!arrest: 22!"
            ]
        },
        {
            "crime": "OTHER NARCOTIC VIOLATION",
            "year": 2009,
            "freq": [
                "!no_arrest: 4!",
                "!arrest: 10!"
            ]
        },
        {
            "crime": "OTHER NARCOTIC VIOLATION",
            "year": 2010,
            "freq": [
                "!no_arrest: 8!",
                "!arrest: 3!"
            ]
        },
        {
            "crime": "OTHER NARCOTIC VIOLATION",
            "year": 2011,
            "freq": [
                "!no_arrest: 2!",
                "!arrest: 3!"
            ]
        },
        {
            "crime": "OTHER OFFENSE",
            "year": 2008,
            "freq": [
                "!no_arrest: 45989!",
                "!arrest: 6988!"
            ]
        },
        {
            "crime": "OTHER OFFENSE",
            "year": 2009,
            "freq": [
                "!no_arrest: 42765!",
                "!arrest: 8400!"
            ]
        },
        {
            "crime": "OTHER OFFENSE",
            "year": 2010,
            "freq": [
                "!no_arrest: 35376!",
                "!arrest: 6238!"
            ]
        },
        {
            "crime": "OTHER OFFENSE",
            "year": 2011,
            "freq": [
                "!no_arrest: 17028!",
                "!arrest: 3170!"
            ]
        },
        {
            "crime": "PROSTITUTION",
            "year": 2008,
            "freq": [
                "!no_arrest: 116!",
                "!arrest: 10138!"
            ]
        },
        {
            "crime": "PROSTITUTION",
            "year": 2009,
            "freq": [
                "!no_arrest: 30!",
                "!arrest: 7849!"
            ]
        },
        {
            "crime": "PROSTITUTION",
            "year": 2010,
            "freq": [
                "!no_arrest: 5!",
                "!arrest: 4638!"
            ]
        },
        {
            "crime": "PROSTITUTION",
            "year": 2011,
            "freq": [
                "!no_arrest: 5!",
                "!arrest: 2419!"
            ]
        },
        {
            "crime": "PUBLIC INDECENCY",
            "year": 2008,
            "freq": [
                "!no_arrest: 2!",
                "!arrest: 6!"
            ]
        },
        {
            "crime": "PUBLIC INDECENCY",
            "year": 2009,
            "freq": [
                "!arrest: 20!"
            ]
        },
        {
            "crime": "PUBLIC INDECENCY",
            "year": 2010,
            "freq": [
                "!arrest: 13!"
            ]
        },
        {
            "crime": "PUBLIC INDECENCY",
            "year": 2011,
            "freq": [
                "!arrest: 13!"
            ]
        },
        {
            "crime": "PUBLIC PEACE VIOLATION",
            "year": 2008,
            "freq": [
                "!no_arrest: 2470!",
                "!arrest: 3551!"
            ]
        },
        {
            "crime": "PUBLIC PEACE VIOLATION",
            "year": 2009,
            "freq": [
                "!no_arrest: 1713!",
                "!arrest: 4572!"
            ]
        },
        {
            "crime": "PUBLIC PEACE VIOLATION",
            "year": 2010,
            "freq": [
                "!no_arrest: 1942!",
                "!arrest: 4892!"
            ]
        },
        {
            "crime": "PUBLIC PEACE VIOLATION",
            "year": 2011,
            "freq": [
                "!no_arrest: 696!",
                "!arrest: 2399!"
            ]
        },
        {
            "crime": "ROBBERY",
            "year": 2008,
            "freq": [
                "!no_arrest: 30016!",
                "!arrest: 3371!"
            ]
        },
        {
            "crime": "ROBBERY",
            "year": 2009,
            "freq": [
                "!no_arrest: 28812!",
                "!arrest: 3118!"
            ]
        },
        {
            "crime": "ROBBERY",
            "year": 2010,
            "freq": [
                "!no_arrest: 24334!",
                "!arrest: 2596!"
            ]
        },
        {
            "crime": "ROBBERY",
            "year": 2011,
            "freq": [
                "!no_arrest: 12666!",
                "!arrest: 1321!"
            ]
        },
        {
            "crime": "SEX OFFENSE",
            "year": 2008,
            "freq": [
                "!no_arrest: 2121!",
                "!arrest: 834!"
            ]
        },
        {
            "crime": "SEX OFFENSE",
            "year": 2009,
            "freq": [
                "!no_arrest: 1654!",
                "!arrest: 821!"
            ]
        },
        {
            "crime": "SEX OFFENSE",
            "year": 2010,
            "freq": [
                "!no_arrest: 1418!",
                "!arrest: 616!"
            ]
        },
        {
            "crime": "SEX OFFENSE",
            "year": 2011,
            "freq": [
                "!no_arrest: 727!",
                "!arrest: 351!"
            ]
        },
        {
            "crime": "STALKING",
            "year": 2008,
            "freq": [
                "!no_arrest: 332!",
                "!arrest: 48!"
            ]
        },
        {
            "crime": "STALKING",
            "year": 2009,
            "freq": [
                "!no_arrest: 288!",
                "!arrest: 46!"
            ]
        },
        {
            "crime": "STALKING",
            "year": 2010,
            "freq": [
                "!no_arrest: 296!",
                "!arrest: 48!"
            ]
        },
        {
            "crime": "STALKING",
            "year": 2011,
            "freq": [
                "!no_arrest: 151!",
                "!arrest: 30!"
            ]
        },
        {
            "crime": "THEFT",

In [51]:
#def writeToJSONFile(path, fileName, data):
    #filePathNameWExt = './' + path + '/' + fileName + '.json'
    #with open(filePathNameWExt, 'w') as fp:
        #json.dump(data, fp)

#writeToJSONFile('./','macfallcheat',json.dumps(records, indent=2,default=default))

In [276]:
import pandas as pd
from collections import defaultdict
import json

data =[('ABC', 'www.example.com/ABC', 10   , 5), ('123', 'www.example.com/123', 9, 4), ('XYZ', 'www.example.com/XYZ', 5, 2), ('ABC111', 'www.example.com/ABC111', 5, 2), ('ABC121', 'www.example.com/ABC121', 5, 2), ('222', 'www.example.com/222', 5, 3), ('abc222', 'www.example.com/abc222', 4, 2), ('ABCaaa', 'www.example.com/ABCaaa', 4, 2)]

df = pd.DataFrame(data, columns=['Name', 'URL', 'Count', 'Rating'])

gp = df.groupby(['Count'])

dict_json = {"name": "flare"}
children = []

for name, group in gp:
    temp = {}
    temp["name"] = name
    temp["children"] = []

    rgp = group.groupby(['Rating'])
    for n, g in rgp:
        temp2 = {}
        temp2["name"] = n
        temp2["children"] = g.reset_index().T.to_dict().values()
        for t in temp2["children"]:
            t["size"] = (t["Rating"] * t["Count"] * 10000) / len(temp2["children"])
            t["name"] = t["Name"]
            del t["Count"]
            del t["Rating"]
            del t["URL"]
            del t["Name"]
            del t["index"]
        temp["children"].append(temp2)
    children.append(temp)

dict_json["children"] = children

def default(o):
    if isinstance(o, np.object): return int(o)  
    raise TypeError

print(json.dumps(list(dict_json), indent=4))

[
    "name",
    "children"
]

### Mapbox

In [2]:
thefts = pd.read_csv('topthefts2018.csv')

In [3]:
thefts.head()

,crime,arrest,date,latitude,longitude,domestic,district,FBI_code,year
0,RETAIL THEFT,False,12/07/2018 05:30:00 PM,41.930906,-87.644017,False,19.0,6,2018
1,OVER $500,False,12/07/2018 12:00:00 PM,41.872742,-87.709326,False,11.0,6,2018
2,OVER $500,False,12/07/2018 12:00:00 PM,41.803672,-87.703846,False,8.0,6,2018
3,OVER $500,False,12/07/2018 08:00:00 PM,41.882389,-87.624375,False,1.0,6,2018
4,OVER $500,False,12/07/2018 08:30:00 PM,41.838217,-87.633226,False,9.0,6,2018